// log in as Test
POST https://localhost:7024/auth/login
Content-Type: application/json

{ "Username" : "werty", "Password" : "werty" }

### // log in as Jakob
POST https://localhost:7024/auth/login
Content-Type: application/json

{ "Username" : "jknr", "Password" : "password" }

### // allow anonymous
GET https://localhost:7024/test/allowanon

### // must be authorized
GET https://localhost:7024/test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiIxZTcwYjE5Yi02YWE4LTQxMGQtYTM2OC01MTM5MDg2MzE0YjgiLCJpYXQiOiIxNS0xMS0yMDIyIDE1OjEwOjA5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IndlcnR5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidGVhY2hlciIsIkRpc3BsYXlOYW1lIjoidHJvcmxzIiwiRW1haWwiOiJzZmRzZkBnZmhnZi5qaCIsIkFnZSI6IjM2IiwiRG9tYWluIjoidmlhIiwiU2VjdXJpdHlMZXZlbCI6IjEiLCJleHAiOjE2Njg1Mjg2MDksImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.kdRtomJigy4Cx3k5hWBfZZ8EKY-7tYBFQhbC80FtJFg_9MP09BP-U8xWzM0SWMregV5cI-EbT_n8N1efquu8mg



###     // policy mustbevia allowed
GET https://localhost:7024/test/mustbevia
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiIyMzYwYWZjNC01ZDQ4LTRlNTctOGYxZC0wYmZlZTFkOWM3ZjIiLCJpYXQiOiIwNi8xMC8yMDIyIDExOjE1OjQxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImprbnIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiRGlzcGxheU5hbWUiOiJKYWtvYiBSYXNtdXNzZW4iLCJFbWFpbCI6Impha29iQGdtYWlsLmNvbSIsIkFnZSI6IjM0IiwiRG9tYWluIjoidmlhIiwiU2VjdXJpdHlMZXZlbCI6IjIiLCJleHAiOjE2NjUwNTg1NDEsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.R1pVBYWQyX_u6W6jJKf2fyVHJvtum3CDgQP3X3otDEI7fQNKZ2yMMA1Pq2Pe5WujGuO0R8nNuqSnVrmL7r8Thg

###    // manual checking MustBeTeacher
GET https://localhost:7024/test/manualcheck
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJkY2JlNTU4Yi1hZjBlLTRmNWUtYWIyNC0wNjBiYzUyZWUxNTkiLCJpYXQiOiIwNy8wOC8yMDIyIDA5OjQ1OjQ4IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImprbnIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiRGlzcGxheU5hbWUiOiJKYWtvYiBSYXNtdXNzZW4iLCJFbWFpbCI6Impha29iQGdtYWlsLmNvbSIsIkFnZSI6IjM0IiwiRG9tYWluIjoiZ21haWwiLCJleHAiOjE2NTk4NjkxNDgsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.3CmYYv_IN9VKHJCLVhyU_y-NNuXO38_TfIoypLdLTTa9QAEbSLdO9h9e2RHIvEIcqJBXScKTLBxwPhihj0obwA





